60 Realisation/Suorce Code/MvcAppMain/MvcAppMain/Models/CT_PhieuKhamBenh.cs
namespace MvcAppMain.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class CT_PhieuKhamBenh
    {
        [Key]
        [Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int ID_PhieuKham { get; set; }

        [Key]
        [Column(Order = 1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int ID_Thuoc { get; set; }

        public int ID_CachDung { get; set; }

        public int? SoLuongThuocLay { get; set; }

        public virtual CachDung CachDung { get; set; }

        public virtual PhieuKhamBenh PhieuKhamBenh { get; set; }

        public virtual Thuoc Thuoc { get; set; }
    }
}

60 Realisation/Suorce Code/MvcAppMain/MvcAppMain/Controllers/CT_PhieuKhamBenhController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using CrystalDecisions.CrystalReports.Engine;
using Microsoft.Reporting.WebForms;
using MvcAppMain.Models;
using MvcAppMain.Report;
using MvcAppMain.Report.DSBaoCaoSuDungThuocTableAdapters;

namespace MvcAppMain.Controllers
{
    public class CT_PhieuKhamBenhController : Controller
    {
        QLPMContext db = new QLPMContext();

        // GET: CT_PhieuKhamBenh
        public ActionResult Index()
        {
            var ct_phieukhambenh = from e in db.CT_PhieuKhamBenh
                                   select e;
            int iD = Convert.ToInt32(Session["ID_PhieuKham"]);
            if (!String.IsNullOrEmpty(iD.ToString())) {
                ct_phieukhambenh = ct_phieukhambenh.Where(s => s.ID_PhieuKham.ToString().Contains(iD.ToString()));
            }
            return View(ct_phieukhambenh.ToList());
            //var cT_PhieuKhamBenh = db.CT_PhieuKhamBenh.Include(c => c.CachDung).Include(c => c.PhieuKhamBenh).Include(c => c.Thuoc);
            //return View(cT_PhieuKhamBenh.ToList());
        }

        public ActionResult BaoCaoSuDungThuoc() {
            var baocaosudungthuoc = db.CT_PhieuKhamBenh.Include(p => p.PhieuKhamBenh).Include(p => p.Thuoc).Include(p => p.CachDung);
            return View(baocaosudungthuoc.ToList());
        }

        //public ActionResult Export()
        //{


        //    ReportDocument rd = new ReportDocument();
        //    rd.Load(Path.Combine(Server.MapPath("~/Report/CRBaoCaoSuDungThuoc.rpt")));
        //    DSBaoCaoSuDungThuoc dataset = new DSBaoCaoSuDungThuoc();
        //    ThuocTableAdapter thuocAdapter = new ThuocTableAdapter();
        //    //HoaDonTableAdapter hoadonAdapter = new HoaDonTableAdapter();
        //    //hoadonAdapter.Fill(dataset.HoaDon);
        //    thuocAdapter.Fill(dataset.Thuoc);

        //    rd.SetDataSource(dataset);
        //    Response.Buffer = false;
        //    Response.ClearContent();
        //    Response.ClearHeaders();

        //    Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
        //    stream.Seek(0, SeekOrigin.Begin);
        //    return File(stream, "application/pdf", "BaoCaoSuDungThuocTheoNgay.pdf");

        //}

        public ActionResult Report()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Report(FormCollection collection)
        {
            try
            {
                int month = Convert.ToInt32(collection["months"].ToString());
                int year = Convert.ToInt32(collection["years"].ToString());

                return RedirectToAction("ReportThuoc", new { m = month,y=year });
            }
            catch (FormatException)
            {
                ModelState.AddModelError("ErrorMessage", "Vui lòng nhập đúng tháng");
                return View();
            }
            catch (Exception)
            {
                ModelState.AddModelError("ErrorMessage", "Vui lòng nhập đúng tháng");
                return View();
            }
        }
        public ActionResult CreateDefaultFolder()
        {
            string rootDirectory = "C:\\ReportThuoc";
            if (!Directory.Exists(rootDirectory))
            {
                Directory.CreateDirectory(rootDirectory);
                ViewBag.Success = "Thành công";
            }
            else
            {
                ModelState.AddModelError("ErrorMessage", "Thư mục đã tồn tại!!");
                return View("Report");
            }
            return View("Report");

        }

        public ActionResult ReportThuoc(int m,int y)
        {
            SetLocalReport(m,y);

            return View();
        }
        private void SetLocalReport(int m,int y)
        {
            ReportViewer reportViewer = new ReportViewer();
            reportViewer.ProcessingMode = ProcessingMode.Local;
            reportViewer.SizeToReportContent = true;
            reportViewer.Width = Unit.Percentage(500);
            reportViewer.Height = Unit.Percentage(500);

            DSBaoCaoSuDungThuoc dataset = new DSBaoCaoSuDungThuoc();
            ThuocTableAdapter thuocTableAdapter = new ThuocTableAdapter();
            thuocTableAdapter.Fill(dataset.Thuoc, m,y);

            reportViewer.LocalReport.ReportPath = Request.MapPath(Request.ApplicationPath) + @"Report\ReportBaoCaoSuDungThuoc.rdlc";
            reportViewer.LocalReport.DataSources.Add(new ReportDataSource("DSBaoCaoSuDungThuoc", dataset.Tables[0]));

            ViewBag.ReportViewer = reportViewer;
        }
        // GET: CT_PhieuKhamBenh/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CT_PhieuKhamBenh cT_PhieuKhamBenh = db.CT_PhieuKhamBenh.Find(id);
            if (cT_PhieuKhamBenh == null)
            {
                return HttpNotFound();
            }
            return View(cT_PhieuKhamBenh);
        }

        // GET: CT_PhieuKhamBenh/Create
        public ActionResult Create()
        {
            ViewBag.ID_CachDung = new SelectList(db.CachDungs, "ID_CachDung", "TenCachDung");
            //ViewBag.ID_PhieuKham = new SelectList(db.PhieuKhamBenhs, "ID_PhieuKham", "TrieuChung");
            ViewBag.ID_PhieuKham = Session["ID_PhieuKham"];
            ViewBag.ID_Thuoc = new SelectList(db.Thuocs, "ID_Thuoc", "TenThuoc");
            //ViewBag.ID_DonVi = new SelectList(db.Thuocs, "ID_Thuoc", "ID_DonVi");
            return View();
        }

        // POST: CT_PhieuKhamBenh/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_PhieuKham,ID_Thuoc,ID_CachDung,SoLuongThuocLay")] CT_PhieuKhamBenh cT_PhieuKhamBenh)
        {
            if (ModelState.IsValid)
            {
                db.CT_PhieuKhamBenh.Add(cT_PhieuKhamBenh);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_CachDung = new SelectList(db.CachDungs, "ID_CachDung", "TenCachDung", cT_PhieuKhamBenh.ID_CachDung);
            ViewBag.ID_PhieuKham = new SelectList(db.PhieuKhamBenhs, "ID_PhieuKham", "TrieuChung", cT_PhieuKhamBenh.ID_PhieuKham);
            ViewBag.ID_Thuoc = new SelectList(db.Thuocs, "ID_Thuoc", "TenThuoc", cT_PhieuKhamBenh.ID_Thuoc);
            return View(cT_PhieuKhamBenh);
        }

        // GET: CT_PhieuKhamBenh/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CT_PhieuKhamBenh cT_PhieuKhamBenh = db.CT_PhieuKhamBenh.Find(id);
            if (cT_PhieuKhamBenh == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_CachDung = new SelectList(db.CachDungs, "ID_CachDung", "TenCachDung", cT_PhieuKhamBenh.ID_CachDung);
            ViewBag.ID_PhieuKham = new SelectList(db.PhieuKhamBenhs, "ID_PhieuKham", "TrieuChung", cT_PhieuKhamBenh.ID_PhieuKham);
            ViewBag.ID_Thuoc = new SelectList(db.Thuocs, "ID_Thuoc", "TenThuoc", cT_PhieuKhamBenh.ID_Thuoc);
            return View(cT_PhieuKhamBenh);
        }

        // POST: CT_PhieuKhamBenh/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_PhieuKham,ID_Thuoc,ID_CachDung,SoLuongThuocLay")] CT_PhieuKhamBenh cT_PhieuKhamBenh)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cT_PhieuKhamBenh).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_CachDung = new SelectList(db.CachDungs, "ID_CachDung", "TenCachDung", cT_PhieuKhamBenh.ID_CachDung);
            ViewBag.ID_PhieuKham = new SelectList(db.PhieuKhamBenhs, "ID_PhieuKham", "TrieuChung", cT_PhieuKhamBenh.ID_PhieuKham);
            ViewBag.ID_Thuoc = new SelectList(db.Thuocs, "ID_Thuoc", "TenThuoc", cT_PhieuKhamBenh.ID_Thuoc);
            return View(cT_PhieuKhamBenh);
        }

        // GET: CT_PhieuKhamBenh/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CT_PhieuKhamBenh cT_PhieuKhamBenh = db.CT_PhieuKhamBenh.Find(id);
            if (cT_PhieuKhamBenh == null)
            {
                return HttpNotFound();
            }
            return View(cT_PhieuKhamBenh);
        }

        // POST: CT_PhieuKhamBenh/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CT_PhieuKhamBenh cT_PhieuKhamBenh = db.CT_PhieuKhamBenh.Find(id);
            db.CT_PhieuKhamBenh.Remove(cT_PhieuKhamBenh);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

60 Realisation/Suorce Code/MvcAppMain/MvcAppMain/Views/CT_PhieuKhamBenh/BaoCaoSuDungThuoc.cshtml
@model IEnumerable<MvcAppMain.Models.CT_PhieuKhamBenh>

@{
    ViewBag.Title = "BaoCaoSuDungThuoc";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>BaoCaoSuDungThuoc</h2>

<p>
    <a class="btn btn-success" href="@Url.Action("Export","CT_PhieuKhamBenh")">Download Report</a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PhieuKhamBenh.NgayKham)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Thuoc.TenThuoc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Thuoc.ID_DonVi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Thuoc.SoLuong)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CachDung.SoLanDung)
        </th>
        
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PhieuKhamBenh.NgayKham)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Thuoc.TenThuoc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Thuoc.ID_DonVi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Thuoc.SoLuong)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CachDung.SoLanDung)
        </td>
    </tr>
}

</table>

60 Realisation/Suorce Code/MvcAppMain/MvcAppMain/Views/CT_PhieuKhamBenh/Create.cshtml
@model MvcAppMain.Models.CT_PhieuKhamBenh

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>THÔNG TIN THUỐC CHO BỆNH NHÂN</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ID_PhieuKham, "Số Phiếu Khám", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBox("ID_PhieuKham", Session["ID_PhieuKham"], htmlAttributes: new { @class = "form-control", @readonly="true"})

            @Html.ValidationMessageFor(model => model.ID_PhieuKham, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ID_Thuoc, "Tên Thuốc", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ID_Thuoc", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ID_Thuoc, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.ID_Thuoc, "ID_DonVi", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ID_DonVi", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ID_Thuoc, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.ID_CachDung, "Cách Dùng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ID_CachDung", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ID_CachDung, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SoLuongThuocLay, "Số Lượng Thuốc Lấy", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SoLuongThuocLay, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoLuongThuocLay, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

60 Realisation/Suorce Code/MvcAppMain/MvcAppMain/Views/CT_PhieuKhamBenh/Delete.cshtml
@model MvcAppMain.Models.CT_PhieuKhamBenh

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CT_PhieuKhamBenh</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CachDung.TenCachDung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CachDung.TenCachDung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhieuKhamBenh.TrieuChung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhieuKhamBenh.TrieuChung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Thuoc.TenThuoc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Thuoc.TenThuoc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongThuocLay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongThuocLay)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

60 Realisation/Suorce Code/MvcAppMain/MvcAppMain/Views/CT_PhieuKhamBenh/Details.cshtml
@model MvcAppMain.Models.CT_PhieuKhamBenh

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>CT_PhieuKhamBenh</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CachDung.TenCachDung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CachDung.TenCachDung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhieuKhamBenh.TrieuChung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhieuKhamBenh.TrieuChung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Thuoc.TenThuoc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Thuoc.TenThuoc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongThuocLay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongThuocLay)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

60 Realisation/Suorce Code/MvcAppMain/MvcAppMain/Views/CT_PhieuKhamBenh/Edit.cshtml
@model MvcAppMain.Models.CT_PhieuKhamBenh

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CT_PhieuKhamBenh</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_PhieuKham)

        @Html.HiddenFor(model => model.ID_Thuoc)

        <div class="form-group">
            @Html.LabelFor(model => model.ID_CachDung, "ID_CachDung", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_CachDung", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_CachDung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongThuocLay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuongThuocLay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuongThuocLay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

60 Realisation/Suorce Code/MvcAppMain/MvcAppMain/Views/CT_PhieuKhamBenh/Index.cshtml
@model IEnumerable<MvcAppMain.Models.CT_PhieuKhamBenh>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>THÔNG TIN KẾT QUẢ KHÁM BỆNH</h2>

<p>
    @Html.ActionLink("Thêm thông khám khác", "Create")
</p>

<table class="table">
    <tr>
        <th>
            @Html.Label("Số Phiếu Khám")
        </th>
        <th>
            @Html.Label("Cách Dùng")
        </th>
        <th>
            @Html.Label("Triệu Chứng")
        </th>
        <th>
            @Html.Label("Tên Thuốc")
        </th>
        <th>
            @Html.Label("Đơn Vị")
        </th>
        <th>
            @Html.Label("Số Lượng Thuốc Lấy")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ID_PhieuKham)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CachDung.TenCachDung)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhieuKhamBenh.TrieuChung)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Thuoc.TenThuoc)
        </td>
        <th>
            @Html.DisplayFor(modelItem => item.Thuoc.ID_DonVi)
        </th>
        <td>
            @Html.DisplayFor(modelItem => item.SoLuongThuocLay)
        </td>
        <td>
            @Html.ActionLink("Chỉnh sửa thông tin", "Edit", new { id = Convert.ToInt32(Session["ID_PhieuKham"]) }) |
            @*@Html.ActionLink("Create", "Create", new { id = Convert.ToInt32(Session["ID_PhieuKham"]) }) |*@
            @Html.ActionLink("Xem thông tin chi tiết", "Details", new { id = Convert.ToInt32(Session["ID_PhieuKham"]) }) |
            @Html.ActionLink("Xóa", "Delete", new { id = Convert.ToInt32(Session["ID_PhieuKham"]) })
        </td>
    </tr>

}

</table>
<a href="/HoaDon/Index">Xem hoa don</a >

60 Realisation/Suorce Code/MvcAppMain/MvcAppMain/Views/CT_PhieuKhamBenh/Report.cshtml
@{
    ViewBag.Title = "Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>
    <div class="form-horizontal" style="margin-top:100px">
        <div class="row">
            <div class="col-md-2 col-sm-2 col-xs-12"></div>

            <div class="col-md-8 col-sm-9 col-xs-12">
                @using (Html.BeginForm("Report", "CT_PhieuKhamBenh", FormMethod.Post, new { @id = "myform" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="panel panel-default">
                        <Center>
                            <h2>BÁO CÁO SỬ DỤNG THUỐC</h2>
                        </Center>
                        <div class="panel-body">
                            <br />
                            @*<div class="form-group">
                                <p style="color:yellow;padding-left:40px">
                                    Vui lòng tạo thư mục chứa Báo cáo.
                                    <a href="/CT_PhieuKhamBenh/CreateDefaultFolder">Click Here</a>
                                </p>
                            </div>*@
                            <div class="form-group">
                                <div class="form-inline center-block">
                                    <div class="form-group col-md-6">
                                        @Html.Label("Tháng:", htmlAttributes: new { @class = "control-label col-md-3" })
                                        <div class="col-md-4">
                                            <table>
                                                <tr>
                                                    <th>
                                                        <input type="text" class="form-control" id="time" name="months">
                                                    </th>
                                                    <th>
                                                        <input type="text" class="form-control" id="time" name="years">
                                                    </th>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td>
                                                        <div class="form-group">
                                                            <div>
                                                                <input type="submit" value="Create" class="btn btn-success" />
                                                            </div>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </table>
                                        </div>
                                    </div>

                                </div>
                                
                                <div class="form-group" style="margin-left:40px;font-size:medium">
                                    @Html.ValidationMessage("ErrorMessage", new { style = "color:red" })
                                    <label style="color:orangered">@ViewBag.Success</label>
                                </div>

                            </div>
                        </div>
                        <label style="color:white;font-style:italic">(*) Vui lòng lưu file vào đường dẫn: C:\ReportThuoc</label>
                    </div>
                }
            </div>
        </div>
    </div>
</body>

60 Realisation/Suorce Code/MvcAppMain/MvcAppMain/Views/CT_PhieuKhamBenh/ReportThuoc.cshtml
@using ReportViewerForMvc;
@{
    ViewBag.Title = "ReportThuoc";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer, new { @style = "width:1000px;height:800px" })